name: MasterDeployCI
on:
  push:
    branches:
      - testBranch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{ secrets.MY_USER_NAME }}
        git config --global user.name ${{ secrets.MY_USER_EMAIL }}
        git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.MY_USER_NAME }}/is74.git
        npm run deploy
